// flow-typed signature: 9b2e9a3bdfa0a74ce30f773d7c775486
// flow-typed version: <<STUB>>/@mui/styled-engine-sc_v^5.1.0/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mui/styled-engine-sc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mui/styled-engine-sc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mui/styled-engine-sc/GlobalStyles/GlobalStyles' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/GlobalStyles' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/legacy/GlobalStyles/GlobalStyles' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/legacy/GlobalStyles' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/legacy' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/legacy/StyledEngineProvider' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/legacy/StyledEngineProvider/StyledEngineProvider' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/modern/GlobalStyles/GlobalStyles' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/modern/GlobalStyles' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/modern' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/modern/StyledEngineProvider' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/modern/StyledEngineProvider/StyledEngineProvider' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/node/GlobalStyles/GlobalStyles' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/node/GlobalStyles' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/node' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/node/StyledEngineProvider' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/node/StyledEngineProvider/StyledEngineProvider' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/StyledEngineProvider' {
  declare module.exports: any;
}

declare module '@mui/styled-engine-sc/StyledEngineProvider/StyledEngineProvider' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mui/styled-engine-sc/GlobalStyles/GlobalStyles.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/GlobalStyles/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/GlobalStyles/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/GlobalStyles/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc'>;
}
declare module '@mui/styled-engine-sc/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc'>;
}
declare module '@mui/styled-engine-sc/legacy/GlobalStyles/GlobalStyles.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/legacy/GlobalStyles/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/legacy/GlobalStyles/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/legacy/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/legacy/GlobalStyles/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/legacy/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/legacy/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/legacy'>;
}
declare module '@mui/styled-engine-sc/legacy/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/legacy'>;
}
declare module '@mui/styled-engine-sc/legacy/StyledEngineProvider/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/legacy/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/legacy/StyledEngineProvider/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/legacy/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/legacy/StyledEngineProvider/StyledEngineProvider.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/legacy/StyledEngineProvider/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/modern/GlobalStyles/GlobalStyles.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/modern/GlobalStyles/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/modern/GlobalStyles/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/modern/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/modern/GlobalStyles/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/modern/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/modern/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/modern'>;
}
declare module '@mui/styled-engine-sc/modern/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/modern'>;
}
declare module '@mui/styled-engine-sc/modern/StyledEngineProvider/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/modern/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/modern/StyledEngineProvider/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/modern/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/modern/StyledEngineProvider/StyledEngineProvider.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/modern/StyledEngineProvider/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/node/GlobalStyles/GlobalStyles.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/node/GlobalStyles/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/node/GlobalStyles/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/node/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/node/GlobalStyles/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/node/GlobalStyles'>;
}
declare module '@mui/styled-engine-sc/node/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/node'>;
}
declare module '@mui/styled-engine-sc/node/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/node'>;
}
declare module '@mui/styled-engine-sc/node/StyledEngineProvider/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/node/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/node/StyledEngineProvider/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/node/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/node/StyledEngineProvider/StyledEngineProvider.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/node/StyledEngineProvider/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/StyledEngineProvider/index' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/StyledEngineProvider/index.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/StyledEngineProvider'>;
}
declare module '@mui/styled-engine-sc/StyledEngineProvider/StyledEngineProvider.js' {
  declare module.exports: $Exports<'@mui/styled-engine-sc/StyledEngineProvider/StyledEngineProvider'>;
}
