// flow-typed signature: ccae0c09b1ec804570e8b4112bc39992
// flow-typed version: <<STUB>>/@mui/styles_v^5.2.3/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mui/styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mui/styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mui/styles/createGenerateClassName/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@mui/styles/createGenerateClassName/createGenerateClassNameHash' {
  declare module.exports: any;
}

declare module '@mui/styles/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@mui/styles/createStyles/createStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/createStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/getStylesCreator/getStylesCreator' {
  declare module.exports: any;
}

declare module '@mui/styles/getStylesCreator' {
  declare module.exports: any;
}

declare module '@mui/styles/getStylesCreator/noopTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/getThemeProps/getThemeProps' {
  declare module.exports: any;
}

declare module '@mui/styles/getThemeProps' {
  declare module.exports: any;
}

declare module '@mui/styles/jssPreset' {
  declare module.exports: any;
}

declare module '@mui/styles/jssPreset/jssPreset' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/createGenerateClassName/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/createGenerateClassName/createGenerateClassNameHash' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/createStyles/createStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/createStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/getStylesCreator/getStylesCreator' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/getStylesCreator' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/getStylesCreator/noopTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/getThemeProps/getThemeProps' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/getThemeProps' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/jssPreset' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/jssPreset/jssPreset' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/makeStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/makeStyles/indexCounter' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/makeStyles/makeStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/makeStyles/multiKeyStore' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/mergeClasses' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/mergeClasses/mergeClasses' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/propsToClassKey' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/propsToClassKey/propsToClassKey' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/ServerStyleSheets/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/styled' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/styled/styled' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/StylesProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/StylesProvider/StylesProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/ThemeProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/useTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/useThemeVariants' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/useThemeVariants/useThemeVariants' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/withStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/withStyles/withStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/withTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/legacy/withTheme/withTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/makeStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/makeStyles/indexCounter' {
  declare module.exports: any;
}

declare module '@mui/styles/makeStyles/makeStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/makeStyles/multiKeyStore' {
  declare module.exports: any;
}

declare module '@mui/styles/mergeClasses' {
  declare module.exports: any;
}

declare module '@mui/styles/mergeClasses/mergeClasses' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/createGenerateClassName/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/createGenerateClassName/createGenerateClassNameHash' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/createStyles/createStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/createStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/getStylesCreator/getStylesCreator' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/getStylesCreator' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/getStylesCreator/noopTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/getThemeProps/getThemeProps' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/getThemeProps' {
  declare module.exports: any;
}

declare module '@mui/styles/modern' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/jssPreset' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/jssPreset/jssPreset' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/makeStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/makeStyles/indexCounter' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/makeStyles/makeStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/makeStyles/multiKeyStore' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/mergeClasses' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/mergeClasses/mergeClasses' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/propsToClassKey' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/propsToClassKey/propsToClassKey' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/ServerStyleSheets/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/styled' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/styled/styled' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/StylesProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/StylesProvider/StylesProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/ThemeProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/useTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/useThemeVariants' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/useThemeVariants/useThemeVariants' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/withStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/withStyles/withStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/withTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/modern/withTheme/withTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/node/createGenerateClassName/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@mui/styles/node/createGenerateClassName/createGenerateClassNameHash' {
  declare module.exports: any;
}

declare module '@mui/styles/node/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@mui/styles/node/createStyles/createStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/node/createStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/node/getStylesCreator/getStylesCreator' {
  declare module.exports: any;
}

declare module '@mui/styles/node/getStylesCreator' {
  declare module.exports: any;
}

declare module '@mui/styles/node/getStylesCreator/noopTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/node/getThemeProps/getThemeProps' {
  declare module.exports: any;
}

declare module '@mui/styles/node/getThemeProps' {
  declare module.exports: any;
}

declare module '@mui/styles/node' {
  declare module.exports: any;
}

declare module '@mui/styles/node/jssPreset' {
  declare module.exports: any;
}

declare module '@mui/styles/node/jssPreset/jssPreset' {
  declare module.exports: any;
}

declare module '@mui/styles/node/makeStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/node/makeStyles/indexCounter' {
  declare module.exports: any;
}

declare module '@mui/styles/node/makeStyles/makeStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/node/makeStyles/multiKeyStore' {
  declare module.exports: any;
}

declare module '@mui/styles/node/mergeClasses' {
  declare module.exports: any;
}

declare module '@mui/styles/node/mergeClasses/mergeClasses' {
  declare module.exports: any;
}

declare module '@mui/styles/node/propsToClassKey' {
  declare module.exports: any;
}

declare module '@mui/styles/node/propsToClassKey/propsToClassKey' {
  declare module.exports: any;
}

declare module '@mui/styles/node/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@mui/styles/node/ServerStyleSheets/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@mui/styles/node/styled' {
  declare module.exports: any;
}

declare module '@mui/styles/node/styled/styled' {
  declare module.exports: any;
}

declare module '@mui/styles/node/StylesProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/node/StylesProvider/StylesProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/node/ThemeProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/node/useTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/node/useThemeVariants' {
  declare module.exports: any;
}

declare module '@mui/styles/node/useThemeVariants/useThemeVariants' {
  declare module.exports: any;
}

declare module '@mui/styles/node/withStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/node/withStyles/withStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/node/withTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/node/withTheme/withTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/propsToClassKey' {
  declare module.exports: any;
}

declare module '@mui/styles/propsToClassKey/propsToClassKey' {
  declare module.exports: any;
}

declare module '@mui/styles/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@mui/styles/ServerStyleSheets/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@mui/styles/styled' {
  declare module.exports: any;
}

declare module '@mui/styles/styled/styled' {
  declare module.exports: any;
}

declare module '@mui/styles/StylesProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/StylesProvider/StylesProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/ThemeProvider' {
  declare module.exports: any;
}

declare module '@mui/styles/useTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/useThemeVariants' {
  declare module.exports: any;
}

declare module '@mui/styles/useThemeVariants/useThemeVariants' {
  declare module.exports: any;
}

declare module '@mui/styles/withStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/withStyles/withStyles' {
  declare module.exports: any;
}

declare module '@mui/styles/withTheme' {
  declare module.exports: any;
}

declare module '@mui/styles/withTheme/withTheme' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mui/styles/createGenerateClassName/createGenerateClassName.js' {
  declare module.exports: $Exports<'@mui/styles/createGenerateClassName/createGenerateClassName'>;
}
declare module '@mui/styles/createGenerateClassName/createGenerateClassNameHash.js' {
  declare module.exports: $Exports<'@mui/styles/createGenerateClassName/createGenerateClassNameHash'>;
}
declare module '@mui/styles/createGenerateClassName/index' {
  declare module.exports: $Exports<'@mui/styles/createGenerateClassName'>;
}
declare module '@mui/styles/createGenerateClassName/index.js' {
  declare module.exports: $Exports<'@mui/styles/createGenerateClassName'>;
}
declare module '@mui/styles/createStyles/createStyles.js' {
  declare module.exports: $Exports<'@mui/styles/createStyles/createStyles'>;
}
declare module '@mui/styles/createStyles/index' {
  declare module.exports: $Exports<'@mui/styles/createStyles'>;
}
declare module '@mui/styles/createStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/createStyles'>;
}
declare module '@mui/styles/getStylesCreator/getStylesCreator.js' {
  declare module.exports: $Exports<'@mui/styles/getStylesCreator/getStylesCreator'>;
}
declare module '@mui/styles/getStylesCreator/index' {
  declare module.exports: $Exports<'@mui/styles/getStylesCreator'>;
}
declare module '@mui/styles/getStylesCreator/index.js' {
  declare module.exports: $Exports<'@mui/styles/getStylesCreator'>;
}
declare module '@mui/styles/getStylesCreator/noopTheme.js' {
  declare module.exports: $Exports<'@mui/styles/getStylesCreator/noopTheme'>;
}
declare module '@mui/styles/getThemeProps/getThemeProps.js' {
  declare module.exports: $Exports<'@mui/styles/getThemeProps/getThemeProps'>;
}
declare module '@mui/styles/getThemeProps/index' {
  declare module.exports: $Exports<'@mui/styles/getThemeProps'>;
}
declare module '@mui/styles/getThemeProps/index.js' {
  declare module.exports: $Exports<'@mui/styles/getThemeProps'>;
}
declare module '@mui/styles/index' {
  declare module.exports: $Exports<'@mui/styles'>;
}
declare module '@mui/styles/index.js' {
  declare module.exports: $Exports<'@mui/styles'>;
}
declare module '@mui/styles/jssPreset/index' {
  declare module.exports: $Exports<'@mui/styles/jssPreset'>;
}
declare module '@mui/styles/jssPreset/index.js' {
  declare module.exports: $Exports<'@mui/styles/jssPreset'>;
}
declare module '@mui/styles/jssPreset/jssPreset.js' {
  declare module.exports: $Exports<'@mui/styles/jssPreset/jssPreset'>;
}
declare module '@mui/styles/legacy/createGenerateClassName/createGenerateClassName.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/createGenerateClassName/createGenerateClassName'>;
}
declare module '@mui/styles/legacy/createGenerateClassName/createGenerateClassNameHash.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/createGenerateClassName/createGenerateClassNameHash'>;
}
declare module '@mui/styles/legacy/createGenerateClassName/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/createGenerateClassName'>;
}
declare module '@mui/styles/legacy/createGenerateClassName/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/createGenerateClassName'>;
}
declare module '@mui/styles/legacy/createStyles/createStyles.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/createStyles/createStyles'>;
}
declare module '@mui/styles/legacy/createStyles/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/createStyles'>;
}
declare module '@mui/styles/legacy/createStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/createStyles'>;
}
declare module '@mui/styles/legacy/getStylesCreator/getStylesCreator.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/getStylesCreator/getStylesCreator'>;
}
declare module '@mui/styles/legacy/getStylesCreator/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/getStylesCreator'>;
}
declare module '@mui/styles/legacy/getStylesCreator/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/getStylesCreator'>;
}
declare module '@mui/styles/legacy/getStylesCreator/noopTheme.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/getStylesCreator/noopTheme'>;
}
declare module '@mui/styles/legacy/getThemeProps/getThemeProps.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/getThemeProps/getThemeProps'>;
}
declare module '@mui/styles/legacy/getThemeProps/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/getThemeProps'>;
}
declare module '@mui/styles/legacy/getThemeProps/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/getThemeProps'>;
}
declare module '@mui/styles/legacy/index' {
  declare module.exports: $Exports<'@mui/styles/legacy'>;
}
declare module '@mui/styles/legacy/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy'>;
}
declare module '@mui/styles/legacy/jssPreset/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/jssPreset'>;
}
declare module '@mui/styles/legacy/jssPreset/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/jssPreset'>;
}
declare module '@mui/styles/legacy/jssPreset/jssPreset.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/jssPreset/jssPreset'>;
}
declare module '@mui/styles/legacy/makeStyles/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/makeStyles'>;
}
declare module '@mui/styles/legacy/makeStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/makeStyles'>;
}
declare module '@mui/styles/legacy/makeStyles/indexCounter.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/makeStyles/indexCounter'>;
}
declare module '@mui/styles/legacy/makeStyles/makeStyles.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/makeStyles/makeStyles'>;
}
declare module '@mui/styles/legacy/makeStyles/multiKeyStore.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/makeStyles/multiKeyStore'>;
}
declare module '@mui/styles/legacy/mergeClasses/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/mergeClasses'>;
}
declare module '@mui/styles/legacy/mergeClasses/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/mergeClasses'>;
}
declare module '@mui/styles/legacy/mergeClasses/mergeClasses.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/mergeClasses/mergeClasses'>;
}
declare module '@mui/styles/legacy/propsToClassKey/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/propsToClassKey'>;
}
declare module '@mui/styles/legacy/propsToClassKey/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/propsToClassKey'>;
}
declare module '@mui/styles/legacy/propsToClassKey/propsToClassKey.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/propsToClassKey/propsToClassKey'>;
}
declare module '@mui/styles/legacy/ServerStyleSheets/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/ServerStyleSheets'>;
}
declare module '@mui/styles/legacy/ServerStyleSheets/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/ServerStyleSheets'>;
}
declare module '@mui/styles/legacy/ServerStyleSheets/ServerStyleSheets.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/ServerStyleSheets/ServerStyleSheets'>;
}
declare module '@mui/styles/legacy/styled/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/styled'>;
}
declare module '@mui/styles/legacy/styled/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/styled'>;
}
declare module '@mui/styles/legacy/styled/styled.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/styled/styled'>;
}
declare module '@mui/styles/legacy/StylesProvider/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/StylesProvider'>;
}
declare module '@mui/styles/legacy/StylesProvider/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/StylesProvider'>;
}
declare module '@mui/styles/legacy/StylesProvider/StylesProvider.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/StylesProvider/StylesProvider'>;
}
declare module '@mui/styles/legacy/ThemeProvider/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/ThemeProvider'>;
}
declare module '@mui/styles/legacy/ThemeProvider/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/ThemeProvider'>;
}
declare module '@mui/styles/legacy/useTheme/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/useTheme'>;
}
declare module '@mui/styles/legacy/useTheme/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/useTheme'>;
}
declare module '@mui/styles/legacy/useThemeVariants/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/useThemeVariants'>;
}
declare module '@mui/styles/legacy/useThemeVariants/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/useThemeVariants'>;
}
declare module '@mui/styles/legacy/useThemeVariants/useThemeVariants.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/useThemeVariants/useThemeVariants'>;
}
declare module '@mui/styles/legacy/withStyles/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/withStyles'>;
}
declare module '@mui/styles/legacy/withStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/withStyles'>;
}
declare module '@mui/styles/legacy/withStyles/withStyles.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/withStyles/withStyles'>;
}
declare module '@mui/styles/legacy/withTheme/index' {
  declare module.exports: $Exports<'@mui/styles/legacy/withTheme'>;
}
declare module '@mui/styles/legacy/withTheme/index.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/withTheme'>;
}
declare module '@mui/styles/legacy/withTheme/withTheme.js' {
  declare module.exports: $Exports<'@mui/styles/legacy/withTheme/withTheme'>;
}
declare module '@mui/styles/makeStyles/index' {
  declare module.exports: $Exports<'@mui/styles/makeStyles'>;
}
declare module '@mui/styles/makeStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/makeStyles'>;
}
declare module '@mui/styles/makeStyles/indexCounter.js' {
  declare module.exports: $Exports<'@mui/styles/makeStyles/indexCounter'>;
}
declare module '@mui/styles/makeStyles/makeStyles.js' {
  declare module.exports: $Exports<'@mui/styles/makeStyles/makeStyles'>;
}
declare module '@mui/styles/makeStyles/multiKeyStore.js' {
  declare module.exports: $Exports<'@mui/styles/makeStyles/multiKeyStore'>;
}
declare module '@mui/styles/mergeClasses/index' {
  declare module.exports: $Exports<'@mui/styles/mergeClasses'>;
}
declare module '@mui/styles/mergeClasses/index.js' {
  declare module.exports: $Exports<'@mui/styles/mergeClasses'>;
}
declare module '@mui/styles/mergeClasses/mergeClasses.js' {
  declare module.exports: $Exports<'@mui/styles/mergeClasses/mergeClasses'>;
}
declare module '@mui/styles/modern/createGenerateClassName/createGenerateClassName.js' {
  declare module.exports: $Exports<'@mui/styles/modern/createGenerateClassName/createGenerateClassName'>;
}
declare module '@mui/styles/modern/createGenerateClassName/createGenerateClassNameHash.js' {
  declare module.exports: $Exports<'@mui/styles/modern/createGenerateClassName/createGenerateClassNameHash'>;
}
declare module '@mui/styles/modern/createGenerateClassName/index' {
  declare module.exports: $Exports<'@mui/styles/modern/createGenerateClassName'>;
}
declare module '@mui/styles/modern/createGenerateClassName/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/createGenerateClassName'>;
}
declare module '@mui/styles/modern/createStyles/createStyles.js' {
  declare module.exports: $Exports<'@mui/styles/modern/createStyles/createStyles'>;
}
declare module '@mui/styles/modern/createStyles/index' {
  declare module.exports: $Exports<'@mui/styles/modern/createStyles'>;
}
declare module '@mui/styles/modern/createStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/createStyles'>;
}
declare module '@mui/styles/modern/getStylesCreator/getStylesCreator.js' {
  declare module.exports: $Exports<'@mui/styles/modern/getStylesCreator/getStylesCreator'>;
}
declare module '@mui/styles/modern/getStylesCreator/index' {
  declare module.exports: $Exports<'@mui/styles/modern/getStylesCreator'>;
}
declare module '@mui/styles/modern/getStylesCreator/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/getStylesCreator'>;
}
declare module '@mui/styles/modern/getStylesCreator/noopTheme.js' {
  declare module.exports: $Exports<'@mui/styles/modern/getStylesCreator/noopTheme'>;
}
declare module '@mui/styles/modern/getThemeProps/getThemeProps.js' {
  declare module.exports: $Exports<'@mui/styles/modern/getThemeProps/getThemeProps'>;
}
declare module '@mui/styles/modern/getThemeProps/index' {
  declare module.exports: $Exports<'@mui/styles/modern/getThemeProps'>;
}
declare module '@mui/styles/modern/getThemeProps/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/getThemeProps'>;
}
declare module '@mui/styles/modern/index' {
  declare module.exports: $Exports<'@mui/styles/modern'>;
}
declare module '@mui/styles/modern/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern'>;
}
declare module '@mui/styles/modern/jssPreset/index' {
  declare module.exports: $Exports<'@mui/styles/modern/jssPreset'>;
}
declare module '@mui/styles/modern/jssPreset/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/jssPreset'>;
}
declare module '@mui/styles/modern/jssPreset/jssPreset.js' {
  declare module.exports: $Exports<'@mui/styles/modern/jssPreset/jssPreset'>;
}
declare module '@mui/styles/modern/makeStyles/index' {
  declare module.exports: $Exports<'@mui/styles/modern/makeStyles'>;
}
declare module '@mui/styles/modern/makeStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/makeStyles'>;
}
declare module '@mui/styles/modern/makeStyles/indexCounter.js' {
  declare module.exports: $Exports<'@mui/styles/modern/makeStyles/indexCounter'>;
}
declare module '@mui/styles/modern/makeStyles/makeStyles.js' {
  declare module.exports: $Exports<'@mui/styles/modern/makeStyles/makeStyles'>;
}
declare module '@mui/styles/modern/makeStyles/multiKeyStore.js' {
  declare module.exports: $Exports<'@mui/styles/modern/makeStyles/multiKeyStore'>;
}
declare module '@mui/styles/modern/mergeClasses/index' {
  declare module.exports: $Exports<'@mui/styles/modern/mergeClasses'>;
}
declare module '@mui/styles/modern/mergeClasses/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/mergeClasses'>;
}
declare module '@mui/styles/modern/mergeClasses/mergeClasses.js' {
  declare module.exports: $Exports<'@mui/styles/modern/mergeClasses/mergeClasses'>;
}
declare module '@mui/styles/modern/propsToClassKey/index' {
  declare module.exports: $Exports<'@mui/styles/modern/propsToClassKey'>;
}
declare module '@mui/styles/modern/propsToClassKey/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/propsToClassKey'>;
}
declare module '@mui/styles/modern/propsToClassKey/propsToClassKey.js' {
  declare module.exports: $Exports<'@mui/styles/modern/propsToClassKey/propsToClassKey'>;
}
declare module '@mui/styles/modern/ServerStyleSheets/index' {
  declare module.exports: $Exports<'@mui/styles/modern/ServerStyleSheets'>;
}
declare module '@mui/styles/modern/ServerStyleSheets/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/ServerStyleSheets'>;
}
declare module '@mui/styles/modern/ServerStyleSheets/ServerStyleSheets.js' {
  declare module.exports: $Exports<'@mui/styles/modern/ServerStyleSheets/ServerStyleSheets'>;
}
declare module '@mui/styles/modern/styled/index' {
  declare module.exports: $Exports<'@mui/styles/modern/styled'>;
}
declare module '@mui/styles/modern/styled/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/styled'>;
}
declare module '@mui/styles/modern/styled/styled.js' {
  declare module.exports: $Exports<'@mui/styles/modern/styled/styled'>;
}
declare module '@mui/styles/modern/StylesProvider/index' {
  declare module.exports: $Exports<'@mui/styles/modern/StylesProvider'>;
}
declare module '@mui/styles/modern/StylesProvider/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/StylesProvider'>;
}
declare module '@mui/styles/modern/StylesProvider/StylesProvider.js' {
  declare module.exports: $Exports<'@mui/styles/modern/StylesProvider/StylesProvider'>;
}
declare module '@mui/styles/modern/ThemeProvider/index' {
  declare module.exports: $Exports<'@mui/styles/modern/ThemeProvider'>;
}
declare module '@mui/styles/modern/ThemeProvider/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/ThemeProvider'>;
}
declare module '@mui/styles/modern/useTheme/index' {
  declare module.exports: $Exports<'@mui/styles/modern/useTheme'>;
}
declare module '@mui/styles/modern/useTheme/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/useTheme'>;
}
declare module '@mui/styles/modern/useThemeVariants/index' {
  declare module.exports: $Exports<'@mui/styles/modern/useThemeVariants'>;
}
declare module '@mui/styles/modern/useThemeVariants/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/useThemeVariants'>;
}
declare module '@mui/styles/modern/useThemeVariants/useThemeVariants.js' {
  declare module.exports: $Exports<'@mui/styles/modern/useThemeVariants/useThemeVariants'>;
}
declare module '@mui/styles/modern/withStyles/index' {
  declare module.exports: $Exports<'@mui/styles/modern/withStyles'>;
}
declare module '@mui/styles/modern/withStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/withStyles'>;
}
declare module '@mui/styles/modern/withStyles/withStyles.js' {
  declare module.exports: $Exports<'@mui/styles/modern/withStyles/withStyles'>;
}
declare module '@mui/styles/modern/withTheme/index' {
  declare module.exports: $Exports<'@mui/styles/modern/withTheme'>;
}
declare module '@mui/styles/modern/withTheme/index.js' {
  declare module.exports: $Exports<'@mui/styles/modern/withTheme'>;
}
declare module '@mui/styles/modern/withTheme/withTheme.js' {
  declare module.exports: $Exports<'@mui/styles/modern/withTheme/withTheme'>;
}
declare module '@mui/styles/node/createGenerateClassName/createGenerateClassName.js' {
  declare module.exports: $Exports<'@mui/styles/node/createGenerateClassName/createGenerateClassName'>;
}
declare module '@mui/styles/node/createGenerateClassName/createGenerateClassNameHash.js' {
  declare module.exports: $Exports<'@mui/styles/node/createGenerateClassName/createGenerateClassNameHash'>;
}
declare module '@mui/styles/node/createGenerateClassName/index' {
  declare module.exports: $Exports<'@mui/styles/node/createGenerateClassName'>;
}
declare module '@mui/styles/node/createGenerateClassName/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/createGenerateClassName'>;
}
declare module '@mui/styles/node/createStyles/createStyles.js' {
  declare module.exports: $Exports<'@mui/styles/node/createStyles/createStyles'>;
}
declare module '@mui/styles/node/createStyles/index' {
  declare module.exports: $Exports<'@mui/styles/node/createStyles'>;
}
declare module '@mui/styles/node/createStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/createStyles'>;
}
declare module '@mui/styles/node/getStylesCreator/getStylesCreator.js' {
  declare module.exports: $Exports<'@mui/styles/node/getStylesCreator/getStylesCreator'>;
}
declare module '@mui/styles/node/getStylesCreator/index' {
  declare module.exports: $Exports<'@mui/styles/node/getStylesCreator'>;
}
declare module '@mui/styles/node/getStylesCreator/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/getStylesCreator'>;
}
declare module '@mui/styles/node/getStylesCreator/noopTheme.js' {
  declare module.exports: $Exports<'@mui/styles/node/getStylesCreator/noopTheme'>;
}
declare module '@mui/styles/node/getThemeProps/getThemeProps.js' {
  declare module.exports: $Exports<'@mui/styles/node/getThemeProps/getThemeProps'>;
}
declare module '@mui/styles/node/getThemeProps/index' {
  declare module.exports: $Exports<'@mui/styles/node/getThemeProps'>;
}
declare module '@mui/styles/node/getThemeProps/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/getThemeProps'>;
}
declare module '@mui/styles/node/index' {
  declare module.exports: $Exports<'@mui/styles/node'>;
}
declare module '@mui/styles/node/index.js' {
  declare module.exports: $Exports<'@mui/styles/node'>;
}
declare module '@mui/styles/node/jssPreset/index' {
  declare module.exports: $Exports<'@mui/styles/node/jssPreset'>;
}
declare module '@mui/styles/node/jssPreset/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/jssPreset'>;
}
declare module '@mui/styles/node/jssPreset/jssPreset.js' {
  declare module.exports: $Exports<'@mui/styles/node/jssPreset/jssPreset'>;
}
declare module '@mui/styles/node/makeStyles/index' {
  declare module.exports: $Exports<'@mui/styles/node/makeStyles'>;
}
declare module '@mui/styles/node/makeStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/makeStyles'>;
}
declare module '@mui/styles/node/makeStyles/indexCounter.js' {
  declare module.exports: $Exports<'@mui/styles/node/makeStyles/indexCounter'>;
}
declare module '@mui/styles/node/makeStyles/makeStyles.js' {
  declare module.exports: $Exports<'@mui/styles/node/makeStyles/makeStyles'>;
}
declare module '@mui/styles/node/makeStyles/multiKeyStore.js' {
  declare module.exports: $Exports<'@mui/styles/node/makeStyles/multiKeyStore'>;
}
declare module '@mui/styles/node/mergeClasses/index' {
  declare module.exports: $Exports<'@mui/styles/node/mergeClasses'>;
}
declare module '@mui/styles/node/mergeClasses/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/mergeClasses'>;
}
declare module '@mui/styles/node/mergeClasses/mergeClasses.js' {
  declare module.exports: $Exports<'@mui/styles/node/mergeClasses/mergeClasses'>;
}
declare module '@mui/styles/node/propsToClassKey/index' {
  declare module.exports: $Exports<'@mui/styles/node/propsToClassKey'>;
}
declare module '@mui/styles/node/propsToClassKey/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/propsToClassKey'>;
}
declare module '@mui/styles/node/propsToClassKey/propsToClassKey.js' {
  declare module.exports: $Exports<'@mui/styles/node/propsToClassKey/propsToClassKey'>;
}
declare module '@mui/styles/node/ServerStyleSheets/index' {
  declare module.exports: $Exports<'@mui/styles/node/ServerStyleSheets'>;
}
declare module '@mui/styles/node/ServerStyleSheets/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/ServerStyleSheets'>;
}
declare module '@mui/styles/node/ServerStyleSheets/ServerStyleSheets.js' {
  declare module.exports: $Exports<'@mui/styles/node/ServerStyleSheets/ServerStyleSheets'>;
}
declare module '@mui/styles/node/styled/index' {
  declare module.exports: $Exports<'@mui/styles/node/styled'>;
}
declare module '@mui/styles/node/styled/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/styled'>;
}
declare module '@mui/styles/node/styled/styled.js' {
  declare module.exports: $Exports<'@mui/styles/node/styled/styled'>;
}
declare module '@mui/styles/node/StylesProvider/index' {
  declare module.exports: $Exports<'@mui/styles/node/StylesProvider'>;
}
declare module '@mui/styles/node/StylesProvider/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/StylesProvider'>;
}
declare module '@mui/styles/node/StylesProvider/StylesProvider.js' {
  declare module.exports: $Exports<'@mui/styles/node/StylesProvider/StylesProvider'>;
}
declare module '@mui/styles/node/ThemeProvider/index' {
  declare module.exports: $Exports<'@mui/styles/node/ThemeProvider'>;
}
declare module '@mui/styles/node/ThemeProvider/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/ThemeProvider'>;
}
declare module '@mui/styles/node/useTheme/index' {
  declare module.exports: $Exports<'@mui/styles/node/useTheme'>;
}
declare module '@mui/styles/node/useTheme/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/useTheme'>;
}
declare module '@mui/styles/node/useThemeVariants/index' {
  declare module.exports: $Exports<'@mui/styles/node/useThemeVariants'>;
}
declare module '@mui/styles/node/useThemeVariants/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/useThemeVariants'>;
}
declare module '@mui/styles/node/useThemeVariants/useThemeVariants.js' {
  declare module.exports: $Exports<'@mui/styles/node/useThemeVariants/useThemeVariants'>;
}
declare module '@mui/styles/node/withStyles/index' {
  declare module.exports: $Exports<'@mui/styles/node/withStyles'>;
}
declare module '@mui/styles/node/withStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/withStyles'>;
}
declare module '@mui/styles/node/withStyles/withStyles.js' {
  declare module.exports: $Exports<'@mui/styles/node/withStyles/withStyles'>;
}
declare module '@mui/styles/node/withTheme/index' {
  declare module.exports: $Exports<'@mui/styles/node/withTheme'>;
}
declare module '@mui/styles/node/withTheme/index.js' {
  declare module.exports: $Exports<'@mui/styles/node/withTheme'>;
}
declare module '@mui/styles/node/withTheme/withTheme.js' {
  declare module.exports: $Exports<'@mui/styles/node/withTheme/withTheme'>;
}
declare module '@mui/styles/propsToClassKey/index' {
  declare module.exports: $Exports<'@mui/styles/propsToClassKey'>;
}
declare module '@mui/styles/propsToClassKey/index.js' {
  declare module.exports: $Exports<'@mui/styles/propsToClassKey'>;
}
declare module '@mui/styles/propsToClassKey/propsToClassKey.js' {
  declare module.exports: $Exports<'@mui/styles/propsToClassKey/propsToClassKey'>;
}
declare module '@mui/styles/ServerStyleSheets/index' {
  declare module.exports: $Exports<'@mui/styles/ServerStyleSheets'>;
}
declare module '@mui/styles/ServerStyleSheets/index.js' {
  declare module.exports: $Exports<'@mui/styles/ServerStyleSheets'>;
}
declare module '@mui/styles/ServerStyleSheets/ServerStyleSheets.js' {
  declare module.exports: $Exports<'@mui/styles/ServerStyleSheets/ServerStyleSheets'>;
}
declare module '@mui/styles/styled/index' {
  declare module.exports: $Exports<'@mui/styles/styled'>;
}
declare module '@mui/styles/styled/index.js' {
  declare module.exports: $Exports<'@mui/styles/styled'>;
}
declare module '@mui/styles/styled/styled.js' {
  declare module.exports: $Exports<'@mui/styles/styled/styled'>;
}
declare module '@mui/styles/StylesProvider/index' {
  declare module.exports: $Exports<'@mui/styles/StylesProvider'>;
}
declare module '@mui/styles/StylesProvider/index.js' {
  declare module.exports: $Exports<'@mui/styles/StylesProvider'>;
}
declare module '@mui/styles/StylesProvider/StylesProvider.js' {
  declare module.exports: $Exports<'@mui/styles/StylesProvider/StylesProvider'>;
}
declare module '@mui/styles/ThemeProvider/index' {
  declare module.exports: $Exports<'@mui/styles/ThemeProvider'>;
}
declare module '@mui/styles/ThemeProvider/index.js' {
  declare module.exports: $Exports<'@mui/styles/ThemeProvider'>;
}
declare module '@mui/styles/useTheme/index' {
  declare module.exports: $Exports<'@mui/styles/useTheme'>;
}
declare module '@mui/styles/useTheme/index.js' {
  declare module.exports: $Exports<'@mui/styles/useTheme'>;
}
declare module '@mui/styles/useThemeVariants/index' {
  declare module.exports: $Exports<'@mui/styles/useThemeVariants'>;
}
declare module '@mui/styles/useThemeVariants/index.js' {
  declare module.exports: $Exports<'@mui/styles/useThemeVariants'>;
}
declare module '@mui/styles/useThemeVariants/useThemeVariants.js' {
  declare module.exports: $Exports<'@mui/styles/useThemeVariants/useThemeVariants'>;
}
declare module '@mui/styles/withStyles/index' {
  declare module.exports: $Exports<'@mui/styles/withStyles'>;
}
declare module '@mui/styles/withStyles/index.js' {
  declare module.exports: $Exports<'@mui/styles/withStyles'>;
}
declare module '@mui/styles/withStyles/withStyles.js' {
  declare module.exports: $Exports<'@mui/styles/withStyles/withStyles'>;
}
declare module '@mui/styles/withTheme/index' {
  declare module.exports: $Exports<'@mui/styles/withTheme'>;
}
declare module '@mui/styles/withTheme/index.js' {
  declare module.exports: $Exports<'@mui/styles/withTheme'>;
}
declare module '@mui/styles/withTheme/withTheme.js' {
  declare module.exports: $Exports<'@mui/styles/withTheme/withTheme'>;
}
