// flow-typed signature: a957744c1d6589ff61789cc1e1001f68
// flow-typed version: <<STUB>>/jwt-decode_v^3.1.2/flow_v0.145.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jwt-decode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jwt-decode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jwt-decode/build/jwt-decode.cjs' {
  declare module.exports: any;
}

declare module 'jwt-decode/build/jwt-decode.esm' {
  declare module.exports: any;
}

declare module 'jwt-decode/build/jwt-decode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jwt-decode/build/jwt-decode.cjs.js' {
  declare module.exports: $Exports<'jwt-decode/build/jwt-decode.cjs'>;
}
declare module 'jwt-decode/build/jwt-decode.esm.js' {
  declare module.exports: $Exports<'jwt-decode/build/jwt-decode.esm'>;
}
declare module 'jwt-decode/build/jwt-decode.js' {
  declare module.exports: $Exports<'jwt-decode/build/jwt-decode'>;
}
