// flow-typed signature: ec4404a1a85c5ea873dfc689bff2bc44
// flow-typed version: <<STUB>>/luxon_v^2.3.0/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'luxon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'luxon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'luxon/build/amd/luxon' {
  declare module.exports: any;
}

declare module 'luxon/build/cjs-browser/luxon' {
  declare module.exports: any;
}

declare module 'luxon/build/es6/luxon' {
  declare module.exports: any;
}

declare module 'luxon/build/global/luxon' {
  declare module.exports: any;
}

declare module 'luxon/build/global/luxon.min' {
  declare module.exports: any;
}

declare module 'luxon/build/node/luxon' {
  declare module.exports: any;
}

declare module 'luxon/src/datetime' {
  declare module.exports: any;
}

declare module 'luxon/src/duration' {
  declare module.exports: any;
}

declare module 'luxon/src/errors' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/conversions' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/diff' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/digits' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/english' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/formats' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/formatter' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/invalid' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/locale' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/regexParser' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/tokenParser' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/util' {
  declare module.exports: any;
}

declare module 'luxon/src/impl/zoneUtil' {
  declare module.exports: any;
}

declare module 'luxon/src/info' {
  declare module.exports: any;
}

declare module 'luxon/src/interval' {
  declare module.exports: any;
}

declare module 'luxon/src/luxon' {
  declare module.exports: any;
}

declare module 'luxon/src/settings' {
  declare module.exports: any;
}

declare module 'luxon/src/zone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/fixedOffsetZone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/IANAZone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/invalidZone' {
  declare module.exports: any;
}

declare module 'luxon/src/zones/systemZone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'luxon/build/amd/luxon.js' {
  declare module.exports: $Exports<'luxon/build/amd/luxon'>;
}
declare module 'luxon/build/cjs-browser/luxon.js' {
  declare module.exports: $Exports<'luxon/build/cjs-browser/luxon'>;
}
declare module 'luxon/build/es6/luxon.js' {
  declare module.exports: $Exports<'luxon/build/es6/luxon'>;
}
declare module 'luxon/build/global/luxon.js' {
  declare module.exports: $Exports<'luxon/build/global/luxon'>;
}
declare module 'luxon/build/global/luxon.min.js' {
  declare module.exports: $Exports<'luxon/build/global/luxon.min'>;
}
declare module 'luxon/build/node/luxon.js' {
  declare module.exports: $Exports<'luxon/build/node/luxon'>;
}
declare module 'luxon/src/datetime.js' {
  declare module.exports: $Exports<'luxon/src/datetime'>;
}
declare module 'luxon/src/duration.js' {
  declare module.exports: $Exports<'luxon/src/duration'>;
}
declare module 'luxon/src/errors.js' {
  declare module.exports: $Exports<'luxon/src/errors'>;
}
declare module 'luxon/src/impl/conversions.js' {
  declare module.exports: $Exports<'luxon/src/impl/conversions'>;
}
declare module 'luxon/src/impl/diff.js' {
  declare module.exports: $Exports<'luxon/src/impl/diff'>;
}
declare module 'luxon/src/impl/digits.js' {
  declare module.exports: $Exports<'luxon/src/impl/digits'>;
}
declare module 'luxon/src/impl/english.js' {
  declare module.exports: $Exports<'luxon/src/impl/english'>;
}
declare module 'luxon/src/impl/formats.js' {
  declare module.exports: $Exports<'luxon/src/impl/formats'>;
}
declare module 'luxon/src/impl/formatter.js' {
  declare module.exports: $Exports<'luxon/src/impl/formatter'>;
}
declare module 'luxon/src/impl/invalid.js' {
  declare module.exports: $Exports<'luxon/src/impl/invalid'>;
}
declare module 'luxon/src/impl/locale.js' {
  declare module.exports: $Exports<'luxon/src/impl/locale'>;
}
declare module 'luxon/src/impl/regexParser.js' {
  declare module.exports: $Exports<'luxon/src/impl/regexParser'>;
}
declare module 'luxon/src/impl/tokenParser.js' {
  declare module.exports: $Exports<'luxon/src/impl/tokenParser'>;
}
declare module 'luxon/src/impl/util.js' {
  declare module.exports: $Exports<'luxon/src/impl/util'>;
}
declare module 'luxon/src/impl/zoneUtil.js' {
  declare module.exports: $Exports<'luxon/src/impl/zoneUtil'>;
}
declare module 'luxon/src/info.js' {
  declare module.exports: $Exports<'luxon/src/info'>;
}
declare module 'luxon/src/interval.js' {
  declare module.exports: $Exports<'luxon/src/interval'>;
}
declare module 'luxon/src/luxon.js' {
  declare module.exports: $Exports<'luxon/src/luxon'>;
}
declare module 'luxon/src/settings.js' {
  declare module.exports: $Exports<'luxon/src/settings'>;
}
declare module 'luxon/src/zone.js' {
  declare module.exports: $Exports<'luxon/src/zone'>;
}
declare module 'luxon/src/zones/fixedOffsetZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/fixedOffsetZone'>;
}
declare module 'luxon/src/zones/IANAZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/IANAZone'>;
}
declare module 'luxon/src/zones/invalidZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/invalidZone'>;
}
declare module 'luxon/src/zones/systemZone.js' {
  declare module.exports: $Exports<'luxon/src/zones/systemZone'>;
}
