// flow-typed signature: 195f0a56c039cb9977569d4118d4378a
// flow-typed version: <<STUB>>/storybook-addon-apollo-client_v^4.0.6/flow_v0.145.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-apollo-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-apollo-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-apollo-client/dist/constants' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-client/dist/decorators' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-client/dist' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-client/dist/panel' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-client/dist/preset/addDecorator' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-client/dist/preset/defaultParameters' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-client/dist/preset' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-client/dist/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-client/dist/title' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-client/dist/types' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-client/preset' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-apollo-client/dist/constants.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist/constants'>;
}
declare module 'storybook-addon-apollo-client/dist/decorators.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist/decorators'>;
}
declare module 'storybook-addon-apollo-client/dist/index' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist'>;
}
declare module 'storybook-addon-apollo-client/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist'>;
}
declare module 'storybook-addon-apollo-client/dist/panel.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist/panel'>;
}
declare module 'storybook-addon-apollo-client/dist/preset/addDecorator.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist/preset/addDecorator'>;
}
declare module 'storybook-addon-apollo-client/dist/preset/defaultParameters.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist/preset/defaultParameters'>;
}
declare module 'storybook-addon-apollo-client/dist/preset/index' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist/preset'>;
}
declare module 'storybook-addon-apollo-client/dist/preset/index.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist/preset'>;
}
declare module 'storybook-addon-apollo-client/dist/register.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist/register'>;
}
declare module 'storybook-addon-apollo-client/dist/title.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist/title'>;
}
declare module 'storybook-addon-apollo-client/dist/types.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/dist/types'>;
}
declare module 'storybook-addon-apollo-client/preset.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-client/preset'>;
}
