// flow-typed signature: 4b81f57b7792d53e4df9bfd943c71a8c
// flow-typed version: <<STUB>>/@graphql-codegen/cli_v1.19.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-codegen/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@graphql-codegen/cli" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@graphql-codegen/cli/bin" {
  declare module.exports: any;
}

declare module "@graphql-codegen/cli/index.cjs" {
  declare module.exports: any;
}

declare module "@graphql-codegen/cli/index.esm" {
  declare module.exports: any;
}

// Filename aliases
declare module "@graphql-codegen/cli/bin.js" {
  declare module.exports: $Exports<"@graphql-codegen/cli/bin">;
}
declare module "@graphql-codegen/cli/index.cjs.js" {
  declare module.exports: $Exports<"@graphql-codegen/cli/index.cjs">;
}
declare module "@graphql-codegen/cli/index.esm.js" {
  declare module.exports: $Exports<"@graphql-codegen/cli/index.esm">;
}
