// flow-typed signature: d0a549c4bac63cc3961fea62654727c1
// flow-typed version: <<STUB>>/@graphql-codegen/flow-operations_v1.18.6/flow_v0.145.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-codegen/flow-operations'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@graphql-codegen/flow-operations' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@graphql-codegen/flow-operations/index.cjs' {
  declare module.exports: any;
}

declare module '@graphql-codegen/flow-operations/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@graphql-codegen/flow-operations/index.cjs.js' {
  declare module.exports: $Exports<'@graphql-codegen/flow-operations/index.cjs'>;
}
declare module '@graphql-codegen/flow-operations/index.esm.js' {
  declare module.exports: $Exports<'@graphql-codegen/flow-operations/index.esm'>;
}
