// flow-typed signature: 63ea313064e64c854f006d58285ca72f
// flow-typed version: <<STUB>>/@graphql-codegen/flow-resolvers_v2.2.2/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-codegen/flow-resolvers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@graphql-codegen/flow-resolvers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@graphql-codegen/flow-resolvers/index' {
  declare module.exports: $Exports<'@graphql-codegen/flow-resolvers'>;
}
declare module '@graphql-codegen/flow-resolvers/index.js' {
  declare module.exports: $Exports<'@graphql-codegen/flow-resolvers'>;
}
