// flow-typed signature: c996c32c5926bd09b5ef1195d04d3a4e
// flow-typed version: <<STUB>>/@graphql-codegen/flow-operations_v2.2.2/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-codegen/flow-operations'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@graphql-codegen/flow-operations' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@graphql-codegen/flow-operations/index' {
  declare module.exports: $Exports<'@graphql-codegen/flow-operations'>;
}
declare module '@graphql-codegen/flow-operations/index.js' {
  declare module.exports: $Exports<'@graphql-codegen/flow-operations'>;
}
