// flow-typed signature: 90615ef203cb8767424c028d21e7b2fe
// flow-typed version: <<STUB>>/@graphql-codegen/flow-resolvers_v1.17.10/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-codegen/flow-resolvers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@graphql-codegen/flow-resolvers" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@graphql-codegen/flow-resolvers/index.cjs" {
  declare module.exports: any;
}

declare module "@graphql-codegen/flow-resolvers/index.esm" {
  declare module.exports: any;
}

// Filename aliases
declare module "@graphql-codegen/flow-resolvers/index.cjs.js" {
  declare module.exports: $Exports<"@graphql-codegen/flow-resolvers/index.cjs">;
}
declare module "@graphql-codegen/flow-resolvers/index.esm.js" {
  declare module.exports: $Exports<"@graphql-codegen/flow-resolvers/index.esm">;
}
