// flow-typed signature: e1b0b912dd5d252e129bc17e7da25798
// flow-typed version: <<STUB>>/@graphql-codegen/introspection_v1.18.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-codegen/introspection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@graphql-codegen/introspection" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@graphql-codegen/introspection/index.cjs" {
  declare module.exports: any;
}

declare module "@graphql-codegen/introspection/index.esm" {
  declare module.exports: any;
}

// Filename aliases
declare module "@graphql-codegen/introspection/index.cjs.js" {
  declare module.exports: $Exports<"@graphql-codegen/introspection/index.cjs">;
}
declare module "@graphql-codegen/introspection/index.esm.js" {
  declare module.exports: $Exports<"@graphql-codegen/introspection/index.esm">;
}
