// flow-typed signature: 67e3bad9cbbb672aeed869d9869a52d4
// flow-typed version: <<STUB>>/@storybook/addon-links_v^6.4.9/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-links/dist/cjs/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/cjs/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/cjs/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/cjs/react/components/link' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/cjs/react/components/RoutedLink' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/cjs/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/cjs/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/cjs/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/esm/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/esm/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/esm/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/esm/react/components/link' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/esm/react/components/RoutedLink' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/esm/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/esm/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/esm/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/modern/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/modern/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/modern/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/modern/react/components/link' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/modern/react/components/RoutedLink' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/modern/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/modern/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/modern/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-links/dist/cjs/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs/constants'>;
}
declare module '@storybook/addon-links/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs'>;
}
declare module '@storybook/addon-links/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs'>;
}
declare module '@storybook/addon-links/dist/cjs/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs/preset/addDecorator'>;
}
declare module '@storybook/addon-links/dist/cjs/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs/preview'>;
}
declare module '@storybook/addon-links/dist/cjs/react/components/link.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs/react/components/link'>;
}
declare module '@storybook/addon-links/dist/cjs/react/components/RoutedLink.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs/react/components/RoutedLink'>;
}
declare module '@storybook/addon-links/dist/cjs/react/index' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs/react'>;
}
declare module '@storybook/addon-links/dist/cjs/react/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs/react'>;
}
declare module '@storybook/addon-links/dist/cjs/register.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs/register'>;
}
declare module '@storybook/addon-links/dist/cjs/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/cjs/typings.d'>;
}
declare module '@storybook/addon-links/dist/esm/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm/constants'>;
}
declare module '@storybook/addon-links/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm'>;
}
declare module '@storybook/addon-links/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm'>;
}
declare module '@storybook/addon-links/dist/esm/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm/preset/addDecorator'>;
}
declare module '@storybook/addon-links/dist/esm/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm/preview'>;
}
declare module '@storybook/addon-links/dist/esm/react/components/link.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm/react/components/link'>;
}
declare module '@storybook/addon-links/dist/esm/react/components/RoutedLink.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm/react/components/RoutedLink'>;
}
declare module '@storybook/addon-links/dist/esm/react/index' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm/react'>;
}
declare module '@storybook/addon-links/dist/esm/react/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm/react'>;
}
declare module '@storybook/addon-links/dist/esm/register.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm/register'>;
}
declare module '@storybook/addon-links/dist/esm/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/esm/typings.d'>;
}
declare module '@storybook/addon-links/dist/modern/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern/constants'>;
}
declare module '@storybook/addon-links/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern'>;
}
declare module '@storybook/addon-links/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern'>;
}
declare module '@storybook/addon-links/dist/modern/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern/preset/addDecorator'>;
}
declare module '@storybook/addon-links/dist/modern/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern/preview'>;
}
declare module '@storybook/addon-links/dist/modern/react/components/link.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern/react/components/link'>;
}
declare module '@storybook/addon-links/dist/modern/react/components/RoutedLink.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern/react/components/RoutedLink'>;
}
declare module '@storybook/addon-links/dist/modern/react/index' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern/react'>;
}
declare module '@storybook/addon-links/dist/modern/react/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern/react'>;
}
declare module '@storybook/addon-links/dist/modern/register.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern/register'>;
}
declare module '@storybook/addon-links/dist/modern/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/modern/typings.d'>;
}
declare module '@storybook/addon-links/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-links/preset'>;
}
declare module '@storybook/addon-links/react.js' {
  declare module.exports: $Exports<'@storybook/addon-links/react'>;
}
declare module '@storybook/addon-links/register.js' {
  declare module.exports: $Exports<'@storybook/addon-links/register'>;
}
