// flow-typed signature: 80754761c117049dc12a740937036b10
// flow-typed version: <<STUB>>/@storybook/addon-essentials_v^6.1.18/flow_v0.145.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-essentials'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-essentials' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-essentials/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/typings.d' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-essentials/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist'>;
}
declare module '@storybook/addon-essentials/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist'>;
}
declare module '@storybook/addon-essentials/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/typings.d'>;
}
