// flow-typed signature: 30671e3e4cf0a5271fdfc928b171b537
// flow-typed version: <<STUB>>/@storybook/addon-essentials_v^6.4.9/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-essentials'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-essentials' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-essentials/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/cjs/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/esm/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/modern/typings.d' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-essentials/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/cjs'>;
}
declare module '@storybook/addon-essentials/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/cjs'>;
}
declare module '@storybook/addon-essentials/dist/cjs/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/cjs/typings.d'>;
}
declare module '@storybook/addon-essentials/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/esm'>;
}
declare module '@storybook/addon-essentials/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/esm'>;
}
declare module '@storybook/addon-essentials/dist/esm/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/esm/typings.d'>;
}
declare module '@storybook/addon-essentials/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/modern'>;
}
declare module '@storybook/addon-essentials/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/modern'>;
}
declare module '@storybook/addon-essentials/dist/modern/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/modern/typings.d'>;
}
