// flow-typed signature: 4b05cb5b4e37c216c6f1c137c9208797
// flow-typed version: <<STUB>>/@storybook/react_v^6.5.0-alpha.5/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react/bin/build' {
  declare module.exports: any;
}

declare module '@storybook/react/bin' {
  declare module.exports: any;
}

declare module '@storybook/react/demo' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/client' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/client/preview/config' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/client/preview/globals' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/client/preview' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/client/preview/render' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/client/preview/types-6-0' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/client/preview/types-6-3' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/client/preview/types-7-0' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/client/preview/types' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/demo/Button' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/demo/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/server/build' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/server/cra-config' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/server/framework-preset-cra' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/server/framework-preset-react-docgen' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/server/framework-preset-react' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/server' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/server/options' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/server/preset' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/cjs/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/client' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/client/preview/config' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/client/preview/globals' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/client/preview' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/client/preview/render' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/client/preview/types-6-0' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/client/preview/types-6-3' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/client/preview/types-7-0' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/client/preview/types' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/demo/Button' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/demo/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/server/build' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/server/cra-config' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/server/framework-preset-cra' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/server/framework-preset-react-docgen' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/server/framework-preset-react' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/server' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/server/options' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/server/preset' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/esm/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/client' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/client/preview/config' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/client/preview/globals' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/client/preview' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/client/preview/render' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/client/preview/types-6-0' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/client/preview/types-6-3' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/client/preview/types-7-0' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/client/preview/types' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/demo/Button' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/demo/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/server/build' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/server/cra-config' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/server/framework-preset-cra' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/server/framework-preset-react-docgen' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/server/framework-preset-react' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/server' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/server/options' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/server/preset' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/modern/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/react/preset' {
  declare module.exports: any;
}

declare module '@storybook/react/standalone' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react/bin/build.js' {
  declare module.exports: $Exports<'@storybook/react/bin/build'>;
}
declare module '@storybook/react/bin/index' {
  declare module.exports: $Exports<'@storybook/react/bin'>;
}
declare module '@storybook/react/bin/index.js' {
  declare module.exports: $Exports<'@storybook/react/bin'>;
}
declare module '@storybook/react/demo.js' {
  declare module.exports: $Exports<'@storybook/react/demo'>;
}
declare module '@storybook/react/dist/cjs/client/index' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client'>;
}
declare module '@storybook/react/dist/cjs/client/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client'>;
}
declare module '@storybook/react/dist/cjs/client/preview/config.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client/preview/config'>;
}
declare module '@storybook/react/dist/cjs/client/preview/globals.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client/preview/globals'>;
}
declare module '@storybook/react/dist/cjs/client/preview/index' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client/preview'>;
}
declare module '@storybook/react/dist/cjs/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client/preview'>;
}
declare module '@storybook/react/dist/cjs/client/preview/render.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client/preview/render'>;
}
declare module '@storybook/react/dist/cjs/client/preview/types-6-0.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client/preview/types-6-0'>;
}
declare module '@storybook/react/dist/cjs/client/preview/types-6-3.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client/preview/types-6-3'>;
}
declare module '@storybook/react/dist/cjs/client/preview/types-7-0.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client/preview/types-7-0'>;
}
declare module '@storybook/react/dist/cjs/client/preview/types.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/client/preview/types'>;
}
declare module '@storybook/react/dist/cjs/demo/Button.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/demo/Button'>;
}
declare module '@storybook/react/dist/cjs/demo/Welcome.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/demo/Welcome'>;
}
declare module '@storybook/react/dist/cjs/server/build.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/server/build'>;
}
declare module '@storybook/react/dist/cjs/server/cra-config.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/server/cra-config'>;
}
declare module '@storybook/react/dist/cjs/server/framework-preset-cra.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/server/framework-preset-cra'>;
}
declare module '@storybook/react/dist/cjs/server/framework-preset-react-docgen.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/server/framework-preset-react-docgen'>;
}
declare module '@storybook/react/dist/cjs/server/framework-preset-react.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/server/framework-preset-react'>;
}
declare module '@storybook/react/dist/cjs/server/index' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/server'>;
}
declare module '@storybook/react/dist/cjs/server/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/server'>;
}
declare module '@storybook/react/dist/cjs/server/options.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/server/options'>;
}
declare module '@storybook/react/dist/cjs/server/preset.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/server/preset'>;
}
declare module '@storybook/react/dist/cjs/typings.d.js' {
  declare module.exports: $Exports<'@storybook/react/dist/cjs/typings.d'>;
}
declare module '@storybook/react/dist/esm/client/index' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client'>;
}
declare module '@storybook/react/dist/esm/client/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client'>;
}
declare module '@storybook/react/dist/esm/client/preview/config.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client/preview/config'>;
}
declare module '@storybook/react/dist/esm/client/preview/globals.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client/preview/globals'>;
}
declare module '@storybook/react/dist/esm/client/preview/index' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client/preview'>;
}
declare module '@storybook/react/dist/esm/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client/preview'>;
}
declare module '@storybook/react/dist/esm/client/preview/render.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client/preview/render'>;
}
declare module '@storybook/react/dist/esm/client/preview/types-6-0.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client/preview/types-6-0'>;
}
declare module '@storybook/react/dist/esm/client/preview/types-6-3.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client/preview/types-6-3'>;
}
declare module '@storybook/react/dist/esm/client/preview/types-7-0.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client/preview/types-7-0'>;
}
declare module '@storybook/react/dist/esm/client/preview/types.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/client/preview/types'>;
}
declare module '@storybook/react/dist/esm/demo/Button.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/demo/Button'>;
}
declare module '@storybook/react/dist/esm/demo/Welcome.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/demo/Welcome'>;
}
declare module '@storybook/react/dist/esm/server/build.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/server/build'>;
}
declare module '@storybook/react/dist/esm/server/cra-config.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/server/cra-config'>;
}
declare module '@storybook/react/dist/esm/server/framework-preset-cra.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/server/framework-preset-cra'>;
}
declare module '@storybook/react/dist/esm/server/framework-preset-react-docgen.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/server/framework-preset-react-docgen'>;
}
declare module '@storybook/react/dist/esm/server/framework-preset-react.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/server/framework-preset-react'>;
}
declare module '@storybook/react/dist/esm/server/index' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/server'>;
}
declare module '@storybook/react/dist/esm/server/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/server'>;
}
declare module '@storybook/react/dist/esm/server/options.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/server/options'>;
}
declare module '@storybook/react/dist/esm/server/preset.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/server/preset'>;
}
declare module '@storybook/react/dist/esm/typings.d.js' {
  declare module.exports: $Exports<'@storybook/react/dist/esm/typings.d'>;
}
declare module '@storybook/react/dist/modern/client/index' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client'>;
}
declare module '@storybook/react/dist/modern/client/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client'>;
}
declare module '@storybook/react/dist/modern/client/preview/config.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client/preview/config'>;
}
declare module '@storybook/react/dist/modern/client/preview/globals.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client/preview/globals'>;
}
declare module '@storybook/react/dist/modern/client/preview/index' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client/preview'>;
}
declare module '@storybook/react/dist/modern/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client/preview'>;
}
declare module '@storybook/react/dist/modern/client/preview/render.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client/preview/render'>;
}
declare module '@storybook/react/dist/modern/client/preview/types-6-0.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client/preview/types-6-0'>;
}
declare module '@storybook/react/dist/modern/client/preview/types-6-3.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client/preview/types-6-3'>;
}
declare module '@storybook/react/dist/modern/client/preview/types-7-0.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client/preview/types-7-0'>;
}
declare module '@storybook/react/dist/modern/client/preview/types.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/client/preview/types'>;
}
declare module '@storybook/react/dist/modern/demo/Button.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/demo/Button'>;
}
declare module '@storybook/react/dist/modern/demo/Welcome.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/demo/Welcome'>;
}
declare module '@storybook/react/dist/modern/server/build.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/server/build'>;
}
declare module '@storybook/react/dist/modern/server/cra-config.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/server/cra-config'>;
}
declare module '@storybook/react/dist/modern/server/framework-preset-cra.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/server/framework-preset-cra'>;
}
declare module '@storybook/react/dist/modern/server/framework-preset-react-docgen.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/server/framework-preset-react-docgen'>;
}
declare module '@storybook/react/dist/modern/server/framework-preset-react.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/server/framework-preset-react'>;
}
declare module '@storybook/react/dist/modern/server/index' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/server'>;
}
declare module '@storybook/react/dist/modern/server/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/server'>;
}
declare module '@storybook/react/dist/modern/server/options.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/server/options'>;
}
declare module '@storybook/react/dist/modern/server/preset.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/server/preset'>;
}
declare module '@storybook/react/dist/modern/typings.d.js' {
  declare module.exports: $Exports<'@storybook/react/dist/modern/typings.d'>;
}
declare module '@storybook/react/preset.js' {
  declare module.exports: $Exports<'@storybook/react/preset'>;
}
declare module '@storybook/react/standalone.js' {
  declare module.exports: $Exports<'@storybook/react/standalone'>;
}
